conditioning:
  method: dae
  params:
    scale: 1  #此处修改，method被修改，1.75

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
    in_shape: !!python/tuple [1, 3, 256, 256]

    # choose from inp_lolcat, inp_lorem, inp, inp_square, 
    #将下方注释中的数据分别放到type中进行运算，使用之前参数最低的那张图，此处修改
    # inp_freeform_10-20%, inp_freeform_20-30%, inp_freeform_30-40%,inp
    type: inp

  # mask_opt:
  #   mask_type: random
  #   # mask_len_range: !!python/tuple [128, 129]  # for box
  #   mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
  #   image_size: 256
  
  noise: 
    name: gaussian
    sigma: 0.05